# Generated by Django 4.2.5 on 2023-09-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0002_remove_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='parentname',
            new_name='parent',
        ),
    ]
