# Generated by Django 4.2.5 on 2023-09-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0003_rename_parentname_member_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='addrs',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='std',
            field=models.IntegerField(default=''),
        ),
    ]
