# Generated by Django 4.2.5 on 2023-09-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0004_member_addrs_member_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='std',
        ),
    ]
