# Generated by Django 4.2.5 on 2023-09-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0005_remove_member_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addrs',
            field=models.CharField(max_length=10),
        ),
    ]
