# Generated by Django 4.2.5 on 2023-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0007_remove_member_addrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adrs',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
