# Generated by Django 4.2.5 on 2023-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0009_alter_member_adrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
