# Generated by Django 4.2.5 on 2023-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0010_member_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
