# Generated by Django 4.2.5 on 2023-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0013_rename_std_member_tel_remove_member_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
