# Generated by Django 4.2.5 on 2023-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1_app', '0014_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.CharField(max_length=20),
        ),
    ]
